// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projet__E_commerce.Data;

#nullable disable

namespace Projet__E_commerce.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projet__E_commerce.Models.Admin", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("localisation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("logo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("nom_cooperative")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("telephone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("ville")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.AdresseLivraison", b =>
                {
                    b.Property<int>("idAdresse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAdresse"));

                    b.Property<string>("adresse_complete")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("code_postal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("est_par_defaut")
                        .HasColumnType("bit");

                    b.Property<int>("idClient")
                        .HasColumnType("int");

                    b.Property<string>("nom_adresse")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("telephone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idAdresse");

                    b.HasIndex("idClient");

                    b.ToTable("AdressesLivraison");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Avis", b =>
                {
                    b.Property<int>("idAvis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAvis"));

                    b.Property<string>("commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("idClient")
                        .HasColumnType("int");

                    b.Property<int>("idProduit")
                        .HasColumnType("int");

                    b.Property<int?>("note")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("idAvis");

                    b.HasIndex("idClient");

                    b.HasIndex("idProduit");

                    b.ToTable("Avis", t =>
                        {
                            t.HasCheckConstraint("CK_Avis_Note", "note BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Projet__E_commerce.Models.BordereauLivraison", b =>
                {
                    b.Property<int>("idBordereau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idBordereau"));

                    b.Property<DateTime>("date_generation")
                        .HasColumnType("datetime2");

                    b.Property<int>("idLivraison")
                        .HasColumnType("int");

                    b.Property<string>("numero_bordereau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("path_bordereau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("idBordereau");

                    b.HasIndex("idLivraison")
                        .IsUnique();

                    b.ToTable("BordereauxLivraison");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Categorie", b =>
                {
                    b.Property<int>("idC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idC"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("idC");

                    b.ToTable("Categories", t =>
                        {
                            t.HasCheckConstraint("CK_Categorie_Nom", "nom IN ('cosmetique', 'nutritive', 'medical', 'artisanat', 'agricole')");
                        });

                    b.HasData(
                        new
                        {
                            idC = 1,
                            created_at = new DateTime(2025, 12, 21, 15, 23, 39, 780, DateTimeKind.Local).AddTicks(8631),
                            description = "Produits cosmétiques et de beauté",
                            nom = "cosmetique",
                            updated_at = new DateTime(2025, 12, 21, 15, 23, 39, 780, DateTimeKind.Local).AddTicks(8695)
                        },
                        new
                        {
                            idC = 2,
                            created_at = new DateTime(2025, 12, 21, 15, 23, 39, 780, DateTimeKind.Local).AddTicks(8701),
                            description = "Produits nutritionnels et alimentaires",
                            nom = "nutritive",
                            updated_at = new DateTime(2025, 12, 21, 15, 23, 39, 780, DateTimeKind.Local).AddTicks(8703)
                        },
                        new
                        {
                            idC = 3,
                            created_at = new DateTime(2025, 12, 21, 15, 23, 39, 780, DateTimeKind.Local).AddTicks(8706),
                            description = "Produits médicaux et de santé",
                            nom = "medical",
                            updated_at = new DateTime(2025, 12, 21, 15, 23, 39, 780, DateTimeKind.Local).AddTicks(8709)
                        },
                        new
                        {
                            idC = 4,
                            created_at = new DateTime(2025, 12, 21, 15, 23, 39, 780, DateTimeKind.Local).AddTicks(8712),
                            description = "Produits artisanaux locaux",
                            nom = "artisanat",
                            updated_at = new DateTime(2025, 12, 21, 15, 23, 39, 780, DateTimeKind.Local).AddTicks(8714)
                        },
                        new
                        {
                            idC = 5,
                            created_at = new DateTime(2025, 12, 21, 15, 23, 39, 780, DateTimeKind.Local).AddTicks(8717),
                            description = "Produits agricoles et fermiers",
                            nom = "agricole",
                            updated_at = new DateTime(2025, 12, 21, 15, 23, 39, 780, DateTimeKind.Local).AddTicks(8719)
                        });
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Client", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("date_naissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("telephone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Commande", b =>
                {
                    b.Property<int>("idCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCommande"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("idClient")
                        .HasColumnType("int");

                    b.Property<decimal>("prixTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("idCommande");

                    b.HasIndex("idClient");

                    b.ToTable("Commandes", t =>
                        {
                            t.HasCheckConstraint("CK_Commande_Statut", "statut IN ('en_attente', 'valide', 'annule')");
                        });
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Facture", b =>
                {
                    b.Property<int>("idFacture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idFacture"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("idCommande")
                        .HasColumnType("int");

                    b.Property<string>("numero_facture")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("path_facture")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("idFacture");

                    b.HasIndex("idCommande")
                        .IsUnique();

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.LigneCommande", b =>
                {
                    b.Property<int>("idLC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLC"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("idCommande")
                        .HasColumnType("int");

                    b.Property<int>("idV")
                        .HasColumnType("int");

                    b.Property<decimal>("prix_unitaire")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("quantite")
                        .HasColumnType("int");

                    b.HasKey("idLC");

                    b.HasIndex("idCommande");

                    b.HasIndex("idV");

                    b.ToTable("LignesCommande");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Livraison", b =>
                {
                    b.Property<int>("idLivraison")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLivraison"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDebutEstimation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateFinEstimation")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("frais")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("idAdresse")
                        .HasColumnType("int");

                    b.Property<int>("idCommande")
                        .HasColumnType("int");

                    b.Property<string>("mode_livraison")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("idLivraison");

                    b.HasIndex("idAdresse");

                    b.HasIndex("idCommande")
                        .IsUnique();

                    b.ToTable("Livraisons", t =>
                        {
                            t.HasCheckConstraint("CK_Livraison_ModeLivraison", "mode_livraison IN ('Standard', 'Express')");

                            t.HasCheckConstraint("CK_Livraison_Statut", "statut IN ('livre', 'non_livre', 'en_cours')");
                        });
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Produit", b =>
                {
                    b.Property<int>("idP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idP"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idAdmin")
                        .HasColumnType("int");

                    b.Property<int>("idC")
                        .HasColumnType("int");

                    b.Property<string>("nomP")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("seuil_alerte")
                        .HasColumnType("int");

                    b.Property<string>("statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("idP");

                    b.HasIndex("idAdmin");

                    b.HasIndex("idC");

                    b.ToTable("Produits", t =>
                        {
                            t.HasCheckConstraint("CK_Produit_Statut", "statut IN ('active', 'inactive')");
                        });
                });

            modelBuilder.Entity("Projet__E_commerce.Models.SuperAdmin", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("SuperAdmins");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Utilisateur", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("est_actif")
                        .HasColumnType("bit");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Variante", b =>
                {
                    b.Property<int>("idV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idV"));

                    b.Property<string>("couleur")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("idP")
                        .HasColumnType("int");

                    b.Property<string>("photo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("poids")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("prix")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("quantite")
                        .HasColumnType("int");

                    b.Property<string>("taille")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("idV");

                    b.HasIndex("idP");

                    b.ToTable("Variantes");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Admin", b =>
                {
                    b.HasOne("Projet__E_commerce.Models.Utilisateur", "Utilisateur")
                        .WithOne()
                        .HasForeignKey("Projet__E_commerce.Models.Admin", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.AdresseLivraison", b =>
                {
                    b.HasOne("Projet__E_commerce.Models.Client", "Client")
                        .WithMany("AdressesLivraison")
                        .HasForeignKey("idClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Avis", b =>
                {
                    b.HasOne("Projet__E_commerce.Models.Client", "Client")
                        .WithMany("Avis")
                        .HasForeignKey("idClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projet__E_commerce.Models.Produit", "Produit")
                        .WithMany("Avis")
                        .HasForeignKey("idProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.BordereauLivraison", b =>
                {
                    b.HasOne("Projet__E_commerce.Models.Livraison", "Livraison")
                        .WithOne("BordereauLivraison")
                        .HasForeignKey("Projet__E_commerce.Models.BordereauLivraison", "idLivraison")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livraison");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Client", b =>
                {
                    b.HasOne("Projet__E_commerce.Models.Utilisateur", "Utilisateur")
                        .WithOne()
                        .HasForeignKey("Projet__E_commerce.Models.Client", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Commande", b =>
                {
                    b.HasOne("Projet__E_commerce.Models.Client", "Client")
                        .WithMany("Commandes")
                        .HasForeignKey("idClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Facture", b =>
                {
                    b.HasOne("Projet__E_commerce.Models.Commande", "Commande")
                        .WithOne("Facture")
                        .HasForeignKey("Projet__E_commerce.Models.Facture", "idCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.LigneCommande", b =>
                {
                    b.HasOne("Projet__E_commerce.Models.Commande", "Commande")
                        .WithMany("LignesCommande")
                        .HasForeignKey("idCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projet__E_commerce.Models.Variante", "Variante")
                        .WithMany("LignesCommande")
                        .HasForeignKey("idV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Livraison", b =>
                {
                    b.HasOne("Projet__E_commerce.Models.AdresseLivraison", "AdresseLivraison")
                        .WithMany("Livraisons")
                        .HasForeignKey("idAdresse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Projet__E_commerce.Models.Commande", "Commande")
                        .WithOne("Livraison")
                        .HasForeignKey("Projet__E_commerce.Models.Livraison", "idCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdresseLivraison");

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Produit", b =>
                {
                    b.HasOne("Projet__E_commerce.Models.Admin", "Admin")
                        .WithMany("Produits")
                        .HasForeignKey("idAdmin")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Projet__E_commerce.Models.Categorie", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("idC")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.SuperAdmin", b =>
                {
                    b.HasOne("Projet__E_commerce.Models.Utilisateur", "Utilisateur")
                        .WithOne()
                        .HasForeignKey("Projet__E_commerce.Models.SuperAdmin", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Variante", b =>
                {
                    b.HasOne("Projet__E_commerce.Models.Produit", "Produit")
                        .WithMany("Variantes")
                        .HasForeignKey("idP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Admin", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.AdresseLivraison", b =>
                {
                    b.Navigation("Livraisons");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Categorie", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Client", b =>
                {
                    b.Navigation("AdressesLivraison");

                    b.Navigation("Avis");

                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Commande", b =>
                {
                    b.Navigation("Facture")
                        .IsRequired();

                    b.Navigation("LignesCommande");

                    b.Navigation("Livraison")
                        .IsRequired();
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Livraison", b =>
                {
                    b.Navigation("BordereauLivraison")
                        .IsRequired();
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Produit", b =>
                {
                    b.Navigation("Avis");

                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("Projet__E_commerce.Models.Variante", b =>
                {
                    b.Navigation("LignesCommande");
                });
#pragma warning restore 612, 618
        }
    }
}
